### ISSUE TITLE
Todos in the code

### ISSUE THREAD

**Issue by jgmuchiri** [Lambda-School-Labs/djhelper-fe#28] opened 2020-03-19 18:28 UTC
https://github.com/Lambda-School-Labs/djhelper-fe/blob/bcf03d7fc3ba8ca1266062f255a6172dcbe11b8d/src/tests/App.test.js#L51

**Comment by ethyl2** [comment] 2020-03-19 21:19
This issue is a duplicate of Issue #28.

**Closed by ethyl2** 2020-03-19 21:19 UTC
